name: Build Mapbox GL Native (Qt)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release, Debug]  # 可以指定构建类型

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Set up Visual Studio 2015
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '2015'

    - name: Install dependencies
      run: |
        pip install clcache
        git config --system core.longpaths true
        git submodule sync
        git submodule update --init
        git submodule foreach git submodule update --init

    - name: Install LLVM
      run: |
        $LLVM_VERSION = "5.0.1"
        $LLVM_HASH = "981543611D719624ACB29A2CFFD6A479CFF36E8AB5EE8A57D8ECA4F9C4C6956F"
        $LLVM_INSTALL_PATH = "C:\\LLVM-$LLVM_VERSION"
        if (-not (Test-Path "$LLVM_INSTALL_PATH\\bin")) {
          Invoke-WebRequest -Uri "https://releases.llvm.org/$LLVM_VERSION/LLVM-$LLVM_VERSION-win64.exe" -OutFile "LLVM-$LLVM_VERSION-win64.exe"
          # Check SHA256 (you can write a script to verify it)
          Start-Process -FilePath "LLVM-$LLVM_VERSION-win64.exe" -ArgumentList '/S',"/D=$LLVM_INSTALL_PATH" -Wait
        }
        setx PATH "$LLVM_INSTALL_PATH\\bin;$env:PATH"

    - name: Install CMake
      run: |
        if (-not (Test-Path "C:\\cmake-3.10.1-win64-x64")) {
          Invoke-WebRequest -Uri "https://cmake.org/files/v3.10/cmake-3.10.1-win64-x64.zip" -OutFile "cmake-3.10.1-win64-x64.zip"
          Expand-Archive -Path "cmake-3.10.1-win64-x64.zip" -DestinationPath "C:\\"
        }
        setx PATH "C:\\cmake-3.10.1-win64-x64\\bin;$env:PATH"

    - name: Set up Qt
      run: |
        setx QT_PREFIX "C:\\Qt\\latest\\msvc2015_64\\lib\\cmake"

    - name: Prepare build directory
      run: |
        mkdir build
        cd build

    - name: Build using CMake
      run: |
        call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" amd64
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_MAKE_PROGRAM="ninja" -DCMAKE_PREFIX_PATH=$QT_PREFIX -DMBGL_WITH_QT=ON ..
        cmake --build . --target qmapboxgl -- -j ${{ github.event.inputs.parallelism || 4 }}

    - name: Cache clcache
      run: clcache -s

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: qmapboxgl.dll
        path: ./build/qmapboxgl.dll
